In [2]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import Markdown, display, HTML

# Fix the dying kernel problem (only a problem in some installations - you can remove it, if it works without it)
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

# Numpy tasks

For a detailed reference check out: https://numpy.org/doc/stable/reference/arrays.indexing.html.

**Task 1.** Calculate the sigmoid (logistic) function on every element of the following numpy array [0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25] and print the last 5 elements. Use only vector operations.

In [3]:
a = np.array([0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25])
print(a)
a = 1/(1 + np.exp(-a))
print(a)

[ 0.3   1.2  -1.4   0.2  -0.1   0.1   0.8  -0.25]
[0.57444252 0.76852478 0.19781611 0.549834   0.47502081 0.52497919
 0.68997448 0.4378235 ]


**Task 2.** Calculate the dot product of the following two vectors:<br/>
$x = [3, 1, 4, 2, 6, 1, 4, 8]$<br/>
$y = [5, 2, 3, 12, 2, 4, 17, 11]$<br/>
a) by using element-wise mutliplication and np.sum,<br/>
b) by using np.dot,<br/>
b) by using np.matmul and transposition (x.T).

In [4]:
x = np.array([3,1,4,2,6,1,4,8])
y = np.array([5,2,3,12,2,4,17,11])
print(np.sum(x*y))
print(np.dot(x,y))
print(np.matmul(x.T,y))

225
225
225


**Task 3.** Calculate value of the logistic model<br/>
$$y = \frac{1}{1 + e^{-x_0 \theta_0 - \ldots - x_9 \theta_9 - \theta_{10}}}$$
for<br/>
$x = [1.2, 2.3, 3.4, -0.7, 4.2, 2.7, -0.5, 1.4, -3.3, 0.2]$<br/>
$\theta = [2.7, 0.33, -2.12, -1.73, 2.9, -5.8, -0.9, 12.11, 3.43, -0.5, -1.65]$<br/>
and print the result. Use only vector operations.

In [5]:
x = np.array([1.2, 2.3, 3.4, -0.7, 4.2, 2.7, -0.5, 1.4, -3.3, 0.2])
theta = np.array([2.7, 0.33, -2.12, -1.73, 2.9, -5.8, -0.9, 12.11, 3.43, -0.5, -1.65])

print(1/(1+np.exp(np.sum(-x*theta[:10])-theta[-1])))

0.2417699832615572


**Task 4.** Calculate value of the multivariate linear regression model<br/>
$$y = A x + B$$
for<br/>
$A = \begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \end{bmatrix}$<br/>
$B = \begin{bmatrix} 0.2 \\ 0.3 \end{bmatrix}$<br/>
$x = [1, 2, 3]^T$<br/>
and print the result. Use only vector and matrix operations.

In [6]:
a = np.array([[1,2,1], [3, 0, 1]])
b = np.array([[0.2], [0.3]])
x = np.array([1,2,3]).T

y = np.add(np.matmul(a,x), b)

print(a*x)

print(y)


[[1 4 3]
 [3 0 3]]
[[8.2 6.2]
 [8.3 6.3]]


# Pandas

## Load datasets

- Steam (https://www.kaggle.com/tamber/steam-video-games)

- MovieLens (https://grouplens.org/datasets/movielens/)

In [7]:
steam_df = pd.read_csv(os.path.join("data", "steam", "steam-200k.csv"), 
                       names=['user-id', 'game-title', 'behavior-name', 'value', 'zero'])

ml_ratings_df = pd.read_csv(os.path.join("data", "movielens_small", "ratings.csv"))
ml_movies_df = pd.read_csv(os.path.join("data", "movielens_small", "movies.csv"))

## Merge both MovieLens DataFrames into one

In [8]:
ml_df = pd.merge(ml_ratings_df, ml_movies_df, on='movieId')
ml_df.head(10)

userId  movieId  rating   timestamp             title  \
0       1        1     4.0   964982703  Toy Story (1995)   
1       5        1     4.0   847434962  Toy Story (1995)   
2       7        1     4.5  1106635946  Toy Story (1995)   
3      15        1     2.5  1510577970  Toy Story (1995)   
4      17        1     4.5  1305696483  Toy Story (1995)   
5      18        1     3.5  1455209816  Toy Story (1995)   
6      19        1     4.0   965705637  Toy Story (1995)   
7      21        1     3.5  1407618878  Toy Story (1995)   
8      27        1     3.0   962685262  Toy Story (1995)   
9      31        1     5.0   850466616  Toy Story (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1  Adventure|Animation|Children|Comedy|Fantasy  
2  Adventure|Animation|Children|Comedy|Fantasy  
3  Adventure|Animation|Children|Comedy|Fantasy  
4  Adventure|Animation|Children|Comedy|Fantasy  
5  Adventure|Animation|Children|Comedy|Fantasy  
6  Adventure|Animation|Children|Comedy|Fantasy  
7  Adventure|Animation|Children|Comedy|Fantasy  
8  Adventure|Animation|Children|Comedy|Fantasy  
9  Adventure|Animation|Children|Comedy|Fantasy

In [9]:
steam_df.head(10)

user-id                  game-title behavior-name  value  zero
0  151603712  The Elder Scrolls V Skyrim      purchase    1.0     0
1  151603712  The Elder Scrolls V Skyrim          play  273.0     0
2  151603712                   Fallout 4      purchase    1.0     0
3  151603712                   Fallout 4          play   87.0     0
4  151603712                       Spore      purchase    1.0     0
5  151603712                       Spore          play   14.9     0
6  151603712           Fallout New Vegas      purchase    1.0     0
7  151603712           Fallout New Vegas          play   12.1     0
8  151603712               Left 4 Dead 2      purchase    1.0     0
9  151603712               Left 4 Dead 2          play    8.9     0

## Pandas tasks - Steam dataset

**Task 5.** How many people made a purchase in the Steam dataset? Remember that a person could buy many games, but you need to count every person once.

In [10]:
len(steam_df.groupby('user-id'))

12393

**Task 6.** How many people made a purchase of "The Elder Scrolls V Skyrim"?

In [11]:
len(steam_df.loc[steam_df['game-title'] == 'The Elder Scrolls V Skyrim'].groupby('user-id'))

717

**Task 7.** How many purchases people made on average?

In [12]:
print(steam_df.loc[steam_df['behavior-name'] == 'purchase'].groupby('user-id').agg({'user-id': 'count'}).mean())


user-id    10.450335
dtype: float64


**Task 8.** Who bought the most games?

In [77]:
list(steam_df.loc[steam_df['behavior-name'] == 'purchase'].groupby('user-id').agg({'value': 'count'}).sort_values('value', ascending = False).head(1).index)[0]


62990992

**Task 9.** How many hours on average people played in "The Elder Scrolls V Skyrim"?

In [29]:
steam_df.loc[(steam_df['behavior-name'] == 'play') & (steam_df['game-title'] == 'The Elder Scrolls V Skyrim')]['value'].mean()

104.71093057607091

**Task 10.** Which games were played the most (in terms of the number of hours played)? Print the first 10 titles and respective numbers of hours.

In [15]:
steam_df.loc[steam_df['behavior-name'] == 'play'].groupby('game-title').agg({'value': 'sum'}).sort_values(by='value', ascending=False).head(10)

value
game-title                                           
Dota 2                                       981684.6
Counter-Strike Global Offensive              322771.6
Team Fortress 2                              173673.3
Counter-Strike                               134261.1
Sid Meier's Civilization V                    99821.3
Counter-Strike Source                         96075.5
The Elder Scrolls V Skyrim                    70889.3
Garry's Mod                                   49725.3
Call of Duty Modern Warfare 2 - Multiplayer   42009.9
Left 4 Dead 2                                 33596.7

**Task 11.** Which games are the most consistently played (in terms of the average number of hours played)? Print the first 10 titles and respective numbers of hours.

In [16]:
steam_df.loc[steam_df['behavior-name'] == 'play'].groupby('game-title').agg({'value': 'mean'}).sort_values(by='value', ascending=False).head(10)

value
game-title                                    
Eastside Hockey Manager            1295.000000
Baldur's Gate II Enhanced Edition   475.255556
FIFA Manager 09                     411.000000
Perpetuum                           400.975000
Football Manager 2014               391.984615
Football Manager 2012               390.453165
Football Manager 2010               375.048571
Football Manager 2011               365.703226
Freaking Meatbags                   331.000000
Out of the Park Baseball 16         330.400000

**Task 12\*\*.** Fix the above for the fact that 0 hours played is not listed, but only a purchase is recorded in such a case.

In [17]:
purchased_df = steam_df.loc[steam_df['behavior-name'] == 'purchase']
played_df = steam_df.loc[steam_df['behavior-name'] == 'play']

pd.merge(purchased_df, played_df, on='user-id', how='left')

user-id                game-title_x behavior-name_x  value_x  \
0        151603712  The Elder Scrolls V Skyrim        purchase      1.0   
1        151603712  The Elder Scrolls V Skyrim        purchase      1.0   
2        151603712  The Elder Scrolls V Skyrim        purchase      1.0   
3        151603712  The Elder Scrolls V Skyrim        purchase      1.0   
4        151603712  The Elder Scrolls V Skyrim        purchase      1.0   
...            ...                         ...             ...      ...   
7637468  128470551                        RUSH        purchase      1.0   
7637469  128470551                        RUSH        purchase      1.0   
7637470  128470551                        RUSH        purchase      1.0   
7637471  128470551                        RUSH        purchase      1.0   
7637472  128470551                        RUSH        purchase      1.0   

         zero_x                game-title_y behavior-name_y  value_y  zero_y  
0             0  The Elder Scrolls V Skyrim            play    273.0     0.0  
1             0                   Fallout 4            play     87.0     0.0  
2             0                       Spore            play     14.9     0.0  
3             0           Fallout New Vegas            play     12.1     0.0  
4             0               Left 4 Dead 2            play      8.9     0.0  
...         ...                         ...             ...      ...     ...  
7637468       0                Fallen Earth            play      2.4     0.0  
7637469       0                 Magic Duels            play      2.2     0.0  
7637470       0                 Titan Souls            play      1.5     0.0  
7637471       0  Grand Theft Auto Vice City            play      1.5     0.0  
7637472       0                        RUSH            play      1.4     0.0  

[7637473 rows x 9 columns]

**Task 13.** Apply the sigmoid function
$$f(x) = \frac{1}{1 + e^{-\frac{1}{100}x}}$$
to hours played and print the first 10 rows from the entire Steam dataset after this change.

In [99]:
def sigm(x):
    return 1/(1+np.exp(-0.01*x))
              
copy_df = steam_df.loc[steam_df['behavior-name'] == 'play'].copy()
copy_df['value'] = copy_df['value'].apply(sigm)
copy_df = pd.merge(copy_df, steam_df, how='right', on=['user-id', 'game-title', 'behavior-name', 'zero']).fillna(1.0)

print(copy_df[['user-id', 'game-title', 'behavior-name', 'value_x']].head(10))

     user-id                  game-title behavior-name   value_x
0  151603712  The Elder Scrolls V Skyrim      purchase  1.000000
1  151603712  The Elder Scrolls V Skyrim          play  0.938774
2  151603712                   Fallout 4      purchase  1.000000
3  151603712                   Fallout 4          play  0.704746
4  151603712                       Spore      purchase  1.000000
5  151603712                       Spore          play  0.537181
6  151603712           Fallout New Vegas      purchase  1.000000
7  151603712           Fallout New Vegas          play  0.530213
8  151603712               Left 4 Dead 2      purchase  1.000000
9  151603712               Left 4 Dead 2          play  0.522235


## Pandas tasks - MovieLens dataset

**Task 14\*.** Calculate popularity (by the number of users who watched a movie) of all genres. Print a DataFrame with two columns: genre, n_users, where n_users contains the number of users who watched a given genre. Sort all genres in descending order.

In [19]:
# Write your code here

**Task 15\*.** Calculate average rating for all genres. Print a DataFrame with two columns: genre, rating, where rating contains the average rating for a given genre. Sort all genres in descending order.

In [20]:
# Write your code here

**Task 17.** Calculate each movie rating bias (deviation from the mean of all movies average rating). Print first 10 in the form: title, average rating, bias.

In [21]:
# Write your code here

**Task 17.** Calculate each user rating bias (deviation from the mean of all users average rating). Print first 10 in the form: user_id, average rating, bias.

In [22]:
# Write your code here

**Task 18.** Randomly choose 10 movies and 10 users and print their interaction matrix in the form of a DataFrame with user_id as index and movie titles as columns. You can iterate over the DataFrame in this task.

In [23]:
# Write your code here

## Pandas + numpy tasks

**Task 19.** Create the entire interaction matrix for the MovieLens dataset. Print the submatrix of first 10 rows and 10 columns.

In [24]:
# Write your code here

**Task 20.** Calculate the matrix of size (n_users, n_users) where at position (i, j) there is the number of movies watched both by user i and user j. Print the submatrix of first 10 rows and 10 columns.

In [25]:
# Write your code here

**Task 21.** Calculate the matrix of size (n_items, n_items) where at position (i, j) there is the number of users who watched both movie i and movie j. To prevent hanging your computer because of RAM shortage use only the first 1000 items. Print the submatrix of first 10 rows and 10 columns.

In [26]:
# Write your code here